nexusbank:
  service:
    name: account-service
    version: 1.0.0

info:
  application:
    name: NEXUSBANK Account Service
    description: Bank account and balance management service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/