nexusbank:
  service:
    name: customer-service
    version: 1.0.0

info:
  application:
    name: NEXUSBANK Customer Service
    description: Customer profile and lifecycle management service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/